[package]
name = "libp2p-bitswap"
version = "0.6.1"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Implementation of the ipfs bitswap protocol."
license = "MIT OR Apache-2.0"
repository = "https://github.com/ipfs-rust/libp2p-bitswap"

[build-dependencies]
prost-build = "0.8"

[dependencies]
async-std = { version = "1.9", features = ["attributes"] }
tiny-cid = "0.2.0"
fnv = "1.0.7"
futures = "0.3.5"
libp2p = "0.46"
log = "0.4.11"
tiny-multihash = "0.4.0"
prost = "0.8"
thiserror = "1.0.20"
unsigned-varint = "0.5.0"

[dev-dependencies]
env_logger = "0.8"
